//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyWealthyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomePP
    {
        public int Id { get; set; }
        public int countryId { get; set; }
        public int yr2005 { get; set; }
        public int yr2006 { get; set; }
        public int yr2007 { get; set; }
        public int yr2008 { get; set; }
        public int yr2009 { get; set; }
        public int yr2010 { get; set; }
        public int yr2011 { get; set; }
        public int yr2012 { get; set; }
        public int yr2013 { get; set; }
        public int yr2014 { get; set; }
        public int yr2015 { get; set; }
        public int yr2016 { get; set; }
        public int yr2017 { get; set; }
        public int yr2018 { get; set; }
        public int yr2019 { get; set; }
        public int yr2020 { get; set; }
        public int yr2021 { get; set; }
        public int yr2022 { get; set; }
        public int yr2023 { get; set; }
        public int yr2024 { get; set; }
        public int yr2025 { get; set; }
        public int yr2026 { get; set; }
        public int yr2027 { get; set; }
        public int yr2028 { get; set; }
        public int yr2029 { get; set; }
        public int yr2030 { get; set; }
        public int yr2031 { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
