//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyWealthyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeYear
    {
        public int Id { get; set; }
        public int countryId { get; set; }
        public double yr2005 { get; set; }
        public double yr2006 { get; set; }
        public double yr2007 { get; set; }
        public double yr2008 { get; set; }
        public double yr2009 { get; set; }
        public double yr2010 { get; set; }
        public double yr2011 { get; set; }
        public double yr2012 { get; set; }
        public double yr2013 { get; set; }
        public double yr2014 { get; set; }
        public double yr2015 { get; set; }
        public double yr2016 { get; set; }
        public double yr2017 { get; set; }
        public double yr2018 { get; set; }
        public double yr2019 { get; set; }
        public double yr2020 { get; set; }
        public double yr2021 { get; set; }
        public double yr2022 { get; set; }
        public double yr2023 { get; set; }
        public double yr2024 { get; set; }
        public double yr2025 { get; set; }
        public double yr2026 { get; set; }
        public double yr2027 { get; set; }
        public double yr2028 { get; set; }
        public double yr2029 { get; set; }
        public double yr2030 { get; set; }
        public double yr2031 { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
